import turtle as trtl
t = trtl.Turtle()

hide = 1
t.speed(0)
if(hide == 1):
    t.hideturtle()

#background
t.pencolor("royal blue")
t.pensize(10000)
t.circle(1)
t.pensize(1)
t.pencolor("black")
#rectangle
t.fillcolor("gainsboro")
t.penup()
t.goto(-100, 150)
t.pendown()
t.begin_fill()
t.forward(200)
t.right(90)
t.forward(100)
t.right(90)
t.forward(200)
t.right(90)
t.forward(100)
t.end_fill()
#leftside
t.begin_fill()
t.left(120)
t.forward(15)
t.back(15)
t.left(60)
t.forward(100)
t.right(120)
t.forward(15)
t.right(60)
t.goto(-113, 142.5)
t.end_fill()
#rightside
t.penup()
t.goto(100, 150)
t.pendown()
t.begin_fill()
t.right(120)
t.forward(15)
t.back(15)
t.right(60)
t.forward(100)
t.left(120)
t.forward(15)
t.goto(113, 142.5)
t.end_fill()
#top
t.penup()
t.goto(-30, 150)
t.pendown()
t.begin_fill()
t.setheading(90)
t.forward(5)
t.right(90)
t.forward(60)
t.right(90)
t.forward(5)
t.end_fill()
#handle
t.fillcolor("sienna")
t.penup()
t.goto(-15, 50)
t.pendown()
t.begin_fill()
t.forward(175)
t.left(90)
t.forward(30)
t.left(90)
t.forward(175)
t.end_fill()
t.left(90)
t.forward(30)
t.right(90)
#horizontallines
t.penup()
t.goto(-113, 142.5)
t.right(90)
t.pendown()
t.forward(225)
t.penup()
t.goto(-113, 57.5)
t.pendown()
t.forward(225)
#runes
t.left(90)
t.penup()
t.goto(-106, 65)
t.pendown()
t.forward(70)
t.penup()
t.goto(106, 65)
t.pendown()
t.forward(70)
#handlelines
t.pencolor("gainsboro")
t.pensize(2)
t.right(90)
t.penup()
t.goto(-15, 30)
t.pendown()
lines = 0
for i in range(8):
    t.forward(30)
    t.penup()
    t.goto(-15, (t.ycor())-20)
    t.pendown()
#animation
loop = 0
count = 0
while(1 == 1):
    if(loop % 32 == 0):
        while(count <= 3):
            t.pencolor("cyan")
            t.fillcolor("cyan")
            t.penup()
            t.goto(-20, 155)
            t.setheading(90)
            t.pendown()
            t.begin_fill()
            t.right(90)
            t.forward(40)
            t.left(90)
            t.forward(300)
            t.left(90)
            t.forward(40)
            t.left(90)
            t.forward(300)
            t.end_fill()
            t.pencolor("white")
            t.fillcolor("white")
            t.penup()
            t.goto(-20, 155)
            t.setheading(90)
            t.pendown()
            t.begin_fill()
            t.right(90)
            t.forward(40)
            t.left(90)
            t.forward(300)
            t.left(90)
            t.forward(40)
            t.left(90)
            t.forward(300)
            t.end_fill()
            count += 1
        t.pencolor("royal blue")
        t.fillcolor("royal blue")
        t.begin_fill()
        t.left(90)
        t.forward(40)
        t.left(90)
        t.forward(300)
        t.left(90)
        t.forward(40)
        t.left(90)
        t.forward(300)
        t.end_fill()
        count = 0
    #1
    tcolor = "cyan"
    t.penup()
    t.pencolor(tcolor)
    t.goto(-60, 150)
    t.pendown()
    t.setheading(130)
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    t.penup()
    t.goto(1000, 1000)
    t.circle(100, 360, 8000)
    tcolor = "royal blue"
    t.pencolor(tcolor)
    t.goto(-60, 150)
    t.setheading(130)
    t.pendown()
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    loop += 1
    #2
    tcolor = "cyan"
    t.penup()
    t.pencolor(tcolor)
    t.goto(-113, 80)
    t.pendown()
    t.setheading(180)
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    t.penup()
    t.goto(1000, 1000)
    t.circle(100, 360, 8000)
    tcolor = "royal blue"
    t.pencolor(tcolor)
    t.goto(-113, 80)
    t.setheading(180)
    t.pendown()
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    loop += 1
    #3
    tcolor = "cyan"
    t.penup()
    t.pencolor(tcolor)
    t.goto(113, 110)
    t.pendown()
    t.setheading(350)
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    t.penup()
    t.goto(1000, 1000)
    t.circle(100, 360, 8000)
    tcolor = "royal blue"
    t.pencolor(tcolor)
    t.goto(113, 110)
    t.setheading(350)
    t.pendown()
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    loop += 1
    #4
    tcolor = "cyan"
    t.penup()
    t.pencolor(tcolor)
    t.goto(60, 150)
    t.pendown()
    t.setheading(375)
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    t.penup()
    t.goto(1000, 1000)
    t.circle(100, 360, 8000)
    tcolor = "royal blue"
    t.pencolor(tcolor)
    t.goto(60, 150)
    t.setheading(375)
    t.pendown()
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    loop += 1
    #5
    tcolor = "cyan"
    t.penup()
    t.pencolor(tcolor)
    t.goto(-113, 110)
    t.pendown()
    t.setheading(155)
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    t.penup()
    t.goto(1000, 1000)
    t.circle(100, 360, 8000)
    tcolor = "royal blue"
    t.pencolor(tcolor)
    t.goto(-113, 110)
    t.setheading(155)
    t.pendown()
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    loop += 1
    #6
    tcolor = "cyan"
    t.penup()
    t.pencolor(tcolor)
    t.goto(113, 80)
    t.pendown()
    t.setheading(325)
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    t.penup()
    t.goto(1000, 1000)
    t.circle(100, 360, 8000)
    tcolor = "royal blue"
    t.pencolor(tcolor)
    t.goto(113, 80)
    t.setheading(325)
    t.pendown()
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    loop += 1
    #7
    tcolor = "cyan"
    t.penup()
    t.pencolor(tcolor)
    t.goto(-60, 50)
    t.pendown()
    t.setheading(205)
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    t.penup()
    t.goto(1000, 1000)
    t.circle(100, 360, 8000)
    tcolor = "royal blue"
    t.pencolor(tcolor)
    t.goto(-60, 50)
    t.setheading(205)
    t.pendown()
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    loop += 1
    #8
    tcolor = "cyan"
    t.penup()
    t.pencolor(tcolor)
    t.goto(60, 50)
    t.pendown()
    t.setheading(300)
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    t.penup()
    t.goto(1000, 1000)
    t.circle(100, 360, 8000)
    tcolor = "royal blue"
    t.pencolor(tcolor)
    t.goto(60, 50)
    t.setheading(300)
    t.pendown()
    t.forward(30)
    t.left(50)
    t.forward(30)
    t.right(30)
    t.forward(30)
    loop += 1

wn = trtl.Screen()
wn.mainloop()