import turtle as trtl
turtle = trtl.Turtle()

hide = 1
turtle.speed(0)
if(hide == 1):
    turtle.hideturtle()

#background
turtle.pencolor("royal blue")
turtle.pensize(10000)
turtle.circle(1)
turtle.pensize(1)
turtle.pencolor("black")
#rectangle
turtle.fillcolor("gainsboro")
turtle.penup()
turtle.goto(-100, 150)
turtle.pendown()
turtle.begin_fill()
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()
#leftside
turtle.begin_fill()
turtle.left(120)
turtle.forward(15)
turtle.back(15)
turtle.left(60)
turtle.forward(100)
turtle.right(120)
turtle.forward(15)
turtle.right(60)
turtle.goto(-113, 142.5)
turtle.end_fill()
#rightside
turtle.penup()
turtle.goto(100, 150)
turtle.pendown()
turtle.begin_fill()
turtle.right(120)
turtle.forward(15)
turtle.back(15)
turtle.right(60)
turtle.forward(100)
turtle.left(120)
turtle.forward(15)
turtle.goto(113, 142.5)
turtle.end_fill()
#top
turtle.penup()
turtle.goto(-30, 150)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(90)
turtle.forward(5)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(5)
turtle.end_fill()
#handle
turtle.fillcolor("sienna")
turtle.penup()
turtle.goto(-15, 50)
turtle.pendown()
turtle.begin_fill()
turtle.forward(175)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(175)
turtle.end_fill()
turtle.left(90)
turtle.forward(30)
turtle.right(90)
#horizontallines
turtle.penup()
turtle.goto(-113, 142.5)
turtle.right(90)
turtle.pendown()
turtle.forward(225)
turtle.penup()
turtle.goto(-113, 57.5)
turtle.pendown()
turtle.forward(225)
#runes
turtle.left(90)
turtle.penup()
turtle.goto(-106, 65)
turtle.pendown()
turtle.forward(70)
turtle.penup()
turtle.goto(106, 65)
turtle.pendown()
turtle.forward(70)
#handlelines
turtle.pencolor("gainsboro")
turtle.pensize(2)
turtle.right(90)
turtle.penup()
turtle.goto(-15, 30)
turtle.pendown()
lines = 0
for i in range(8):
    turtle.forward(30)
    turtle.penup()
    turtle.goto(-15, (turtle.ycor())-20)
    turtle.pendown()
#animation
loop = 0
count = 0
while(1 == 1):
    #big lightning
    if(loop % 32 == 0):
        while(count <= 3):
            turtle.pencolor("cyan")
            turtle.fillcolor("cyan")
            turtle.penup()
            turtle.goto(-20, 155)
            turtle.setheading(90)
            turtle.pendown()
            turtle.begin_fill()
            turtle.right(90)
            turtle.forward(40)
            turtle.left(90)
            turtle.forward(400)
            turtle.left(90)
            turtle.forward(40)
            turtle.left(90)
            turtle.forward(400)
            turtle.end_fill()
            turtle.pencolor("white")
            turtle.fillcolor("white")
            turtle.penup()
            turtle.goto(-20, 155)
            turtle.setheading(90)
            turtle.pendown()
            turtle.begin_fill()
            turtle.right(90)
            turtle.forward(40)
            turtle.left(90)
            turtle.forward(400)
            turtle.left(90)
            turtle.forward(40)
            turtle.left(90)
            turtle.forward(400)
            turtle.end_fill()
            count += 1
        turtle.pencolor("royal blue")
        turtle.fillcolor("royal blue")
        turtle.begin_fill()
        turtle.left(90)
        turtle.forward(40)
        turtle.left(90)
        turtle.forward(400)
        turtle.left(90)
        turtle.forward(40)
        turtle.left(90)
        turtle.forward(400)
        turtle.end_fill()
        count = 0
    #small lightning
    #1 (top right)
    tcolor = "cyan"
    turtle.penup()
    turtle.pencolor(tcolor)
    turtle.goto(-60, 150)
    turtle.pendown()
    turtle.setheading(130)
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    turtle.penup()
    turtle.goto(1000, 1000)
    turtle.circle(100, 360, 8000)
    tcolor = "royal blue"
    turtle.pencolor(tcolor)
    turtle.goto(-60, 150)
    turtle.setheading(130)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    loop += 1
    #2 (lower middle left)
    tcolor = "cyan"
    turtle.penup()
    turtle.pencolor(tcolor)
    turtle.goto(-113, 80)
    turtle.pendown()
    turtle.setheading(180)
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    turtle.penup()
    turtle.goto(1000, 1000)
    turtle.circle(100, 360, 8000)
    tcolor = "royal blue"
    turtle.pencolor(tcolor)
    turtle.goto(-113, 80)
    turtle.setheading(180)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    loop += 1
    #3 (upper middle right)
    tcolor = "cyan"
    turtle.penup()
    turtle.pencolor(tcolor)
    turtle.goto(113, 110)
    turtle.pendown()
    turtle.setheading(350)
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    turtle.penup()
    turtle.goto(1000, 1000)
    turtle.circle(100, 360, 8000)
    tcolor = "royal blue"
    turtle.pencolor(tcolor)
    turtle.goto(113, 110)
    turtle.setheading(350)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    loop += 1
    #4 (top right)
    tcolor = "cyan"
    turtle.penup()
    turtle.pencolor(tcolor)
    turtle.goto(60, 150)
    turtle.pendown()
    turtle.setheading(375)
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    turtle.penup()
    turtle.goto(1000, 1000)
    turtle.circle(100, 360, 8000)
    tcolor = "royal blue"
    turtle.pencolor(tcolor)
    turtle.goto(60, 150)
    turtle.setheading(375)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    loop += 1
    #5 (upper middle left)
    tcolor = "cyan"
    turtle.penup()
    turtle.pencolor(tcolor)
    turtle.goto(-113, 110)
    turtle.pendown()
    turtle.setheading(155)
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    turtle.penup()
    turtle.goto(1000, 1000)
    turtle.circle(100, 360, 8000)
    tcolor = "royal blue"
    turtle.pencolor(tcolor)
    turtle.goto(-113, 110)
    turtle.setheading(155)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    loop += 1
    #6 (lower middle right)
    tcolor = "cyan"
    turtle.penup()
    turtle.pencolor(tcolor)
    turtle.goto(113, 80)
    turtle.pendown()
    turtle.setheading(325)
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    turtle.penup()
    turtle.goto(1000, 1000)
    turtle.circle(100, 360, 8000)
    tcolor = "royal blue"
    turtle.pencolor(tcolor)
    turtle.goto(113, 80)
    turtle.setheading(325)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    loop += 1
    #7 (bottom left)
    tcolor = "cyan"
    turtle.penup()
    turtle.pencolor(tcolor)
    turtle.goto(-60, 50)
    turtle.pendown()
    turtle.setheading(205)
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    turtle.penup()
    turtle.goto(1000, 1000)
    turtle.circle(100, 360, 8000)
    tcolor = "royal blue"
    turtle.pencolor(tcolor)
    turtle.goto(-60, 50)
    turtle.setheading(205)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    loop += 1
    #8 (bottom right)
    tcolor = "cyan"
    turtle.penup()
    turtle.pencolor(tcolor)
    turtle.goto(60, 50)
    turtle.pendown()
    turtle.setheading(300)
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    turtle.penup()
    turtle.goto(1000, 1000)
    turtle.circle(100, 360, 8000)
    tcolor = "royal blue"
    turtle.pencolor(tcolor)
    turtle.goto(60, 50)
    turtle.setheading(300)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(50)
    turtle.forward(30)
    turtle.right(30)
    turtle.forward(30)
    loop += 1

wn = trtl.Screen()
wn.mainloop()
